version: "3.7"
services:
  api:
    build:
      context: ../
      dockerfile: docker/workspace/Dockerfile
      args:
        - UID
        - GID
        - DOCKER_USER
    image: ${COMPOSE_PROJECT_NAME}-workspace
    ports:
      - ${API_PORT}:3000
    volumes:
      - ../server:/home/${DOCKER_USER}/app:cached
    stdin_open: true
    tty: true

  mariadb:
    image: mariadb:10.3.16
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${COMPOSE_PROJECT_NAME}
      MYSQL_USER: ${COMPOSE_PROJECT_NAME}
      MYSQL_PASSWORD: ${COMPOSE_PROJECT_NAME}
    volumes:
      - mariadb:/var/lib/mysql
    command: --character-set-server=utf8 --collation-server=utf8_general_ci

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - ${PHPMYADMIN_PORT}:80
    volumes:
      - phpmyadmin:/sessions

volumes:
  mariadb:
  phpmyadmin:
